
$("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'> <a href='https://ya-f3.com/'>شات انفاس للجوال</a></div>").insertAfter($(".loginstat"))

$("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'> <a href='https://ya-f3.com/'>دردشة انفاس للجوال</a></div>").insertAfter($(".loginstat"))

$("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'> <a href='https://ya-f3.com/'>شات انفاس </a></div>").insertAfter($(".loginstat"))

$("<div class='fr borderg' style='padding:2px;background-color:white;margin-right:4px;'> <a href='https://ya-f3.com/'>شات صوتي كتابي </a></div>").insertAfter($(".loginstat"))
$(`<a href="https://instabio.cc/3102511mK1SUh" target="_blank" style=" width: 100%; "  id="asim33" class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"> للتواصل عبر مواقعنا </div></a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');
$(`<div><marquee direction="right" width="100%" id="des0" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="4"> أهلاً وسهلا بكم في شات <font color="#357524" class="des2"> { أنفـآإس للجؤال </font>افضل حضور الاسبوع<font class="des2" color="#800000"> ( قريباً ) </font>مبدع الشات <font class="des2" color="#223366"> ( قريباً ) </font>افضل روم لهذا الاسبوع<font class="des2" color="#ff00ff"> ( قريباُ )   </font>افضل سوبر هذا الآسبوع  <font class="des2" color="#5CAD9A"> ( قريباً ) </font>مبدع الحائط لهذا الاسبوع<font class="des2" color="#800000"> قريباً </font>مع تمنياتنا للجميع باطيب الاوقات  </marquee></div>`).insertBefore('.lonline.light.break');
$(` <center><div width="99%" id="asim7"><font style="background-color:#FFFFFF;color:#2f4749;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" > 
 ( متنفس الآقلأم والقلوب)  </font></div><center>`).insertBefore('div#d2bc');
$(".tboxbc").attr("placeholder", "اطلق العنان لقلمك وابدع");
$("#l1>button,#l2>button").click(function(){alert('   اهلآإ بكم فيء عائلتنا عائلة شات انفاس للجوال     ')})
$(`<div style=" color: #FC1717;text-align: center;margin-bottom: 10px; font-family:'jazeera-light', Fontawesome"> إعلانات شات انفاس  للضروره فقط </div>`).insertBefore('span.fl.fa.fa-send');
$(`<a href="https://coolnames.online/English-decoration" target="_blank" style=" width: 30%; "  id="asim33" class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">زخرفة</div></a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');
$(`<center><div style="position: static;width: 100%;" onclick="setTimeout(function(){fixSize();},800);"><div width="99.5%" id="design-a"style="background-color: antiquewhite;color: #105873;border-bottom: 3px solid #105873;border-top: 3px solid #6b5f5f;padding-bottom: 2px;border-radius: 0px 0px 15px 15px;" ><font id="sultan" class=" sultan11"><u><b>الاشتراكــات</b></u> </font><div id="spanan" style="font-family: jazeera-light, FontAwesome;color: red;text-align: right;display:none;" ><p style="text-align: center"><b><font color="#000080">اشتراكات الشات</font></b></p></p><div style="float: right;padding-right: 20px;">- 1</div> تاج ذهبي بخاصية ( المخفي ) + ( سوبر فضي هديه ) بـ 13 عضو لمدة : شهرين <img src="https://www.ya-f3.com/sico/1549292642761.gif"></p><div style="float: right;padding-right: 20px;">- 2</div> تاج اسود ملكي بخاصية ( المخفي ) بـ 10 اعضاء لمدة : شهرين <img src="https://www.ya-f3.com/sico/1636478666807.gif"></p><div style="float: right;padding-right: 20px;">- 3</div> تاج فضي بـ 8 اعضاء لمدة : شهرين <img src="https://www.ya-f3.com/sico/1636478691763.gif"> </p><div style="float: right;padding-right: 20px;">- 4</div> نجمه ذهبيه بـ 6 اعضاء لمدة : شهرين <img src="https://www.ya-f3.com/sico/1634645924410.gif"></p><div style="float: right;padding-right: 20px;">- 5</div> نجمه سوداء بـ 4 اعضاء لمدة : شهر <img src="https://www.ya-f3.com/sico/1636478854796.gif"></p><div style="float: right;padding-right: 20px;">- 6</div> نجمه فضيه بـ 3 اعضاء لمدة : شهر <img src="https://www.ya-f3.com/sico/1636478996675.gif"><p><b>ومن اراد بنر لـ اسمه بـ 5 اعضاء مع التصميم ولمدة شهر</font></b><p style="text-align: center"><u><b><a target="_blank" href="https://wa.me/qr/3JW5SDULZI6WD1">وللتواصل مع الاداره اضغط هنا</a></b></u><></div> </div></div><center>`).insertBefore('#d2');$("#design-a").click(function(){$("#spanan").slideToggle(function(){});});
